QQuickImagePreviewProvider: Add missing include for std::lock_guard
This fixes the following build failure seen with a
local -no-pch build:

    .../qt5/qtmultimedia/src/multimediaquick/qquickimagepreviewprovider.cpp:16:14: error: no member named 'lock_guard' in namespace 'std'
       16 |         std::lock_guard guard(mutex);
          |         ~~~~~^
    .../qt5/qtmultimedia/src/multimediaquick/qquickimagepreviewprovider.cpp:16:25: error: use of undeclared identifier 'guard'
       16 |         std::lock_guard guard(mutex);

This amends d3508f485257a43ae4e91cb85dc608b0c9d20256.

Change-Id: I2ee0354d6089f098a01d4f1625d1e94848016748
Reviewed-by: Tim Blechmann <tim.blechmann@qt.io>