QAudioHelpers: fix C++20 -Werror,-Wdeprecated-enum-float-conversion
Says Clang 10.0.0 -std=c++20:

qaudiohelpers.cpp:71:44: error: arithmetic between enumeration type 'QAudioHelperInternal::signedVersion<unsigned char>::(anonymous enum at /home/marc/Qt/qt5/qtmultimedia/src/multimedia/audio/qaudiohelpers.cpp:63:5)' and floating-point type 'double' is deprecated [-Werror,-Wdeprecated-enum-float-conversion]
        pDst[i] = signedVersion<T>::offset + ((typename signedVersion<T>::TS)(pSrc[i] - signedVersion<T>::offset) * factor);
                  ~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix by turning the enum { offset } into a static constexpr int
instead.

Task-number: QTBUG-104172
Change-Id: I92a22583fc5e1fc524364b64701aa8d416b82671
Reviewed-by: Lars Knoll <lars.knoll@gmail.com>
(cherry picked from commit 94d43085b3f3327b2bf2d644c5f984391f608d3a)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>