QGstUtils: fix build with MSVC
MSVC didn't like the #iffery that was done with GST_STATIC_CAPS(). The
build error was:

    qtmultimedia\src\gsttools\qgstutils.cpp(1323): error C2121: '#':
invalid character: possibly the result of a macro expansion
    qtmultimedia\src\gsttools\qgstutils.cpp(1323): error C2059: syntax
error: 'if'
    qtmultimedia\src\gsttools\qgstutils.cpp(1323): error C2143: syntax
error: missing ';' before '{'
    qtmultimedia\src\gsttools\qgstutils.cpp(1311): error C2143: syntax
error: missing ';' before '}'
    qtmultimedia\src\gsttools\qgstutils.cpp(1325): error C2059: syntax
error: 'return'
    qtmultimedia\src\gsttools\qgstutils.cpp(1326): error C2059: syntax
error: '}'
    qtmultimedia\src\gsttools\qgstutils.cpp(1326): error C2143: syntax
error: missing ';' before '}'
    qtmultimedia\src\gsttools\qgstutils.cpp(1329): error C2143: syntax
error: missing ';' before '{'
    qtmultimedia\src\gsttools\qgstutils.cpp(1329): error C2447: '{':
missing function header (old-style formal list?)

Change-Id: Ic9ac64648aba396fc4ef433e73d5c72a8c1c3da1
Reviewed-by: VaL Doroshchuk <valentyn.doroshchuk@qt.io>