Compile in C++11 mode: the Q_DECLARE_METATYPE must be visible
The error was:
tests/auto/integration/qdeclarativevideooutput/tst_qdeclarativevideooutput.cpp:113:62:   required from here
qmetatype.h:637:5: error: static assertion failed: Type is not registered, please use Q_DECLARE_METATYPE macro to make it know to Qt's meta-object system

Change-Id: Id4e29803de646cbad0d401b1fe0e0b38e458d12f
Reviewed-by: Michael Goddard <michael.goddard@nokia.com>
Reviewed-by: Marc Mutz <marc.mutz@kdab.com>
Reviewed-by: Jonas Rabbe <jonas.rabbe@gmail.com>