ffmpeg: add include for timeval
Fix build issue with missing include:

src/plugins/multimedia/ffmpeg/qv4l2camera_p.h:149:5: error: 'timeval' does not name a type
|   149 |     timeval firstFrameTime = {-1, -1};
|       |     ^~~~~~~

Pick-to: 6.6 6.5
Change-Id: Iaca7514633cdaf439f5f7960cc5191f106c3f15a
Reviewed-by: Artem Dyomin <artem.dyomin@qt.io>