Add missing includes
qwindowsaudiodeviceinfo.cpp(132): error C2027: use of undefined type 'QIODevice'
qwindowsaudiooutput.h(151): error C2504: 'QIODevice': base class undefined

Change-Id: I64c3f90f19936eb6db65b8a71980d19ceacc1b1c
Reviewed-by: Val Doroshchuk <valentyn.doroshchuk@qt.io>