GStreamer: Add missing include for Qt::HANDLE
Amends da66d7957aff93e97f1d68e0653b9a2c6e64e971 to fix this
build error seen in a Clang -no-pch build on Debian testing:

In file included from .../qt5/qtmultimedia/src/plugins/multimedia/gstreamer/common/qgstreameregldisplay.cpp:4:
.../qt5/qtmultimedia/src/plugins/multimedia/gstreamer/common/qgstreameregldisplay_p.h:23:1: error: use of undeclared identifier 'Qt'
   23 | Qt::HANDLE qGstEglDisplay();
      | ^
1 error generated.

Pick-to: 6.8
Change-Id: I36bbacfd1f43f905bb71a57799cd3c7b1b95857c
Reviewed-by: Tim Blechmann <tim.blechmann@qt.io>
(cherry picked from commit fe6ca66b0606fa924697550afc4aff4e9ee3b1a1)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit 6c334943ca412d8c3490048a2ed7a0a6a9ddaf94)