Fix compilation error under VS2019 19.29
Does not compile, error C3493: 'masterStreamType' cannot be implicitly
captured because no default capture mode has been specified

Pick-to: 6.4
Change-Id: I9e046d037ed233777a0d442557d23cb3acbbee75
Reviewed-by: Artem Dyomin <artem.dyomin@qt.io>
Reviewed-by: Lars Knoll <lars@knoll.priv.no>