ffmpeg: add include for timeval
Fix build issue with missing include:

src/plugins/multimedia/ffmpeg/qv4l2camera_p.h:149:5: error: 'timeval' does not name a type
|   149 |     timeval firstFrameTime = {-1, -1};
|       |     ^~~~~~~

Pick-to: 6.5
Change-Id: Iaca7514633cdaf439f5f7960cc5191f106c3f15a
Reviewed-by: Artem Dyomin <artem.dyomin@qt.io>
(cherry picked from commit 79533b4b45308ca0a345b8ee3e5b1628bb52a6bc)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>