Fix build issue with conflicting declarations in GL headers
Some graphics stacks have old version of GL/GLES headers which have conflicting
declaration and fail when GL and GLES headers are used at the same time.

/usr/include/GL/glext.h:466:19: error: conflicting declaration 'typedef ptrdiff_t GLsizeiptr'
 | typedef ptrdiff_t GLsizeiptr;
 |                   ^~~~~~~~

/usr/include/GLES3/gl3.h:75:25: note: previous declaration as 'typedef khronos_ssize_t GLsizeiptr'
 | typedef khronos_ssize_t GLsizeiptr;
 |                         ^~~~~~~~~~

Pick-to: 6.2
Change-Id: I98b96755ea1b27c942214adf3d76e65539302053
Reviewed-by: Lars Knoll <lars.knoll@qt.io>