GStreamer: remove constexpr from QGstPipeline
It might have supported constexpr initialization, but the use of
QUniqueHandle implied a load-time cost anyway to install the destructor
atexit() time.

And now QUniqueHandle no longer allows constexpr.

qgstpipeline_p.h:34:15: error: explicitly defaulted function ‘constexpr QGstPipeline::QGstPipeline()’ cannot be declared ‘constexpr’ because the implicit declaration is not ‘constexpr’:
qgst_p.h:805:7: note: defaulted constructor calls non-‘constexpr’ ‘QGstBin::QGstBin()’
qgst_p.h:556:7: note: defaulted constructor calls non-‘constexpr’ ‘QGstElement::QGstElement()’
qgst_p.h:381:7: note: defaulted constructor calls non-‘constexpr’ ‘QGstObject::QGstObject()’
qsharedhandle_p.h:102:5: note: defaulted constructor calls non-‘constexpr’ ‘QtPrivate::QSharedHandle<HandleTraits>::QSharedHandle() [with HandleTraits = QSharedGstObjectTraits]’
quniquehandle_p.h:196:14: note: defaulted constructor calls non-‘constexpr’ ‘QUniqueHandle<HandleTraits, Deleter>::QUniqueHandle(const Type&) [with typename std::enable_if<is_default_constructible_v<Deleter>, bool>::type <anonymous> = 1; HandleTraits = QtPrivate::UniqueHandleTraitsFromSharedHandleTraits<QSharedGstObjectTraits>; Deleter = QtUniqueHandleTraits::DefaultDeleter<QtPrivate::UniqueHandleTraitsFromSharedHandleTraits<QSharedGstObjectTraits> >; Type = GstObject*]’

Change-Id: I6c8153900d510dcc9309fffd827a5a9c03b0a97b
Reviewed-by: Tim Blechmann <tim.blechmann@qt.io>