Fix build: av_stream_get_side_data() takes an int* in ffmpeg n4.x
qffmpegmediadataholder.cpp:54:90: error:
cannot convert ‘size_t*’ {aka ‘long unsigned int*’} to ‘int*’

Change-Id: Ib84fc618ac204205bf7afffd1773ee1138d86d37
Reviewed-by: Artem Dyomin <artem.dyomin@qt.io>
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>
Reviewed-by: Qt CI Bot <qt_ci_bot@qt-project.org>
(cherry picked from commit 5f201b08ab086f53009f14be241c739f2b89e6c6)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>