QAmbisonicDecoder: fix Clang 15 -Werror,-Warray-parameter
Says Clang 15:

  qambisonicdecoder.cpp:267:84: error: argument 'reverb' of type 'const float *[]' with mismatched bound [-Werror,-Warray-parameter]
  void QAmbisonicDecoder::processBufferWithReverb(const float *input[], const float *reverb[], short *output, int nSamples)
                                                                                     ^
  qambisonicdecoder_p.h:51:69: note: previously declared as 'const float *[2]' here
      void processBufferWithReverb(const float *input[], const float *reverb[2], short *output, int nSamples);
                                                                      ^

Fix by using the same array bound in the definition as was declared.

Amends 0eede8f08dc06e3c46eb2ffddd765fbc37184187.

Pick-to: 6.4
Change-Id: I3bdd44ff1d3263f35bef1d01f64e285b200e9acc
Reviewed-by: Paul Olav Tvete <paul.tvete@qt.io>