Fix warning on iOS
  error: unused function 'qLcDarwinMediaDevices'
  [-Werror,-Wunused-function]

The logging category is so far only used on macOS, so declare it only
there.

Change-Id: Ifeb847dfc54d59b617bd30505b61b27290d0c381
Reviewed-by: Lars Knoll <lars@knoll.priv.no>
(cherry picked from commit 8024029a57e73a10ab0792eb1d1605fa6bef7ef3)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>