qffmpeghwaccel: Add QElapsedTimer include
This fixes the following build error seen in a local
-no-pch Clang 19 build:

    [9/177] Building CXX object qtmultimedia/src/plugins/multimedia/ffmpeg/CMakeFiles/FFmpegMediaPluginImplPrivate.dir/qffmpeghwaccel.cpp.o
    FAILED: qtmultimedia/src/plugins/multimedia/ffmpeg/CMakeFiles/FFmpegMediaPluginImplPrivate.dir/qffmpeghwaccel.cpp.o
    /usr/bin/ccache /usr/bin/clang++ -DQT_ASCII_CAST_WARNINGS -DQT_BUILDING_QT -DQT_BUILD_FFMPEGMEDIAPLUGINIMPL_LIB -DQT_COMPILING_FFMPEG -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_EXPLICIT_QFILE_CONSTRUCTION_FROM_PATH -DQT_GUI_LIB -DQT_MOC_COMPAT -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_NO_AS_CONST=1 -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NO_CONTEXTLESS_CONNECT=1 -DQT_NO_EXCEPTIONS -DQT_NO_FOREACH -DQT_NO_FOREACH=1 -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_QASCONST -DQT_NO_QEXCHANGE -DQT_NO_QSNPRINTF -DQT_NO_STD_FORMAT_SUPPORT -DQT_OPENGL_LIB -DQT_QMLINTEGRATION_LIB -DQT_QMLMETA_LIB -DQT_QMLMODELS_LIB -DQT_QMLWORKERSCRIPT_LIB -DQT_QML_LIB -DQT_QUICK_LIB -DQT_STRICT_QLIST_ITERATORS -DQT_USE_QSTRINGBUILDER -DQ_FFMPEG_PLUGIN_STUBS_ONLY -DVA_NEEDED_SOVERSION=\"2\" -D_GLIBCXX_ASSERTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/home/michi/development/git/qt5/qtmultimedia/src/plugins/multimedia/ffmpeg/FFmpegMediaPluginImplPrivate_autogen/include -I/home/michi/development/git/qt5/qtbase/include -I/home/michi/development/git/qt5/qtbase/include/QtFFmpegMediaPluginImpl -I/home/michi/development/git/qt5/qtmultimedia/src/plugins/multimedia/ffmpeg -I/home/michi/development/git/qt5/qtbase/include/QtFFmpegMediaPluginImpl/6.10.0 -I/home/michi/development/git/qt5/qtbase/include/QtFFmpegMediaPluginImpl/6.10.0/QtFFmpegMediaPluginImpl -I/home/michi/development/git/qt5/qtmultimedia/src/multimedia -I/home/michi/development/git/qt5/qtbase/include/QtMultimedia/6.10.0 -I/home/michi/development/git/qt5/qtbase/include/QtMultimedia/6.10.0/QtMultimedia -I/home/michi/development/git/qt5/qtbase/src/corelib -I/home/michi/development/git/qt5/qtbase/include/QtCore/6.10.0 -I/home/michi/development/git/qt5/qtbase/include/QtCore/6.10.0/QtCore -I/home/michi/development/git/qt5/qtbase/include/QtCore -I/home/michi/development/git/qt5/qtbase/mkspecs/linux-clang -I/home/michi/development/git/qt5/qtbase/src/gui -I/home/michi/development/git/qt5/qtbase/include/QtGui/6.10.0 -I/home/michi/development/git/qt5/qtbase/include/QtGui/6.10.0/QtGui -I/home/michi/development/git/qt5/qtbase/include/QtGui -I/home/michi/development/git/qt5/qtbase/include/QtMultimedia -I/home/michi/development/git/qt5/qtbase/include/QtNetwork -I/home/michi/development/git/qt5/qtbase/include/QtOpenGL -I/home/michi/development/git/qt5/qtbase/src/opengl -I/home/michi/development/git/qt5/qtbase/include/QtOpenGL/6.10.0 -I/home/michi/development/git/qt5/qtbase/include/QtOpenGL/6.10.0/QtOpenGL -I/home/michi/development/git/qt5/qtbase/include/QtQuick -I/home/michi/development/git/qt5/qtbase/include/QtQml -I/home/michi/development/git/qt5/qtbase/include/QtQmlIntegration -I/home/michi/development/git/qt5/qtdeclarative/src/qmlintegration -I/home/michi/development/git/qt5/qtbase/include/QtQmlMeta -I/home/michi/development/git/qt5/qtbase/include/QtQmlModels -I/home/michi/development/git/qt5/qtbase/include/QtQmlWorkerScript -isystem /home/michi/development/git/qt5/qtmultimedia/src/plugins/multimedia/ffmpeg/../../../3rdparty/signalsmith-stretch -D_GLIBCXX_DEBUG -g -std=gnu++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -fPIC -Werror "-Wno-error=#warnings" -Wno-error=deprecated-declarations -Wno-error=deprecated-enum-enum-conversion -Wno-error=deprecated-copy-with-user-provided-copy -Wno-error=unused-but-set-variable -fcf-protection=full -ftrivial-auto-var-init=pattern -fstack-protector-strong -fno-exceptions -MD -MT qtmultimedia/src/plugins/multimedia/ffmpeg/CMakeFiles/FFmpegMediaPluginImplPrivate.dir/qffmpeghwaccel.cpp.o -MF qtmultimedia/src/plugins/multimedia/ffmpeg/CMakeFiles/FFmpegMediaPluginImplPrivate.dir/qffmpeghwaccel.cpp.o.d -o qtmultimedia/src/plugins/multimedia/ffmpeg/CMakeFiles/FFmpegMediaPluginImplPrivate.dir/qffmpeghwaccel.cpp.o -c /home/michi/development/git/qt5/qtmultimedia/src/plugins/multimedia/ffmpeg/qffmpeghwaccel.cpp
    /home/michi/development/git/qt5/qtmultimedia/src/plugins/multimedia/ffmpeg/qffmpeghwaccel.cpp:143:9: error: unknown type name 'QElapsedTimer'
      143 |         QElapsedTimer timer;
          |         ^
    1 error generated.
    ninja: build stopped: subcommand failed.

Pick-to: 6.9 6.8
Change-Id: I288956bb7a64901e3aa27e04abb532dbf00a7a0f
Reviewed-by: Tim Blechmann <tim.blechmann@qt.io>