FFMPEG: when using VAAPI, link to VAAPI
When FFMPEG_STUBS does not contain "va", the stub mechanism is not in
use and VAAPI::VAAPI should be linked directly. The previous code fell
into the private-stub path unconditionally (due to `va_stub_index
EQUAL -1`), which does not link libva, leaving the three symbols used
by qffmpeghwaccel_vaapi.cpp unresolved:

in function `QFFmpeg::VAAPITextureConverter::createTextureHandles(AVFrame*, std::unique_ptr<QVideoFrameTexturesHandles, std::default_delete<QVideoFrameTexturesHandles> >)':
src/plugins/multimedia/ffmpeg/qffmpeghwaccel_vaapi.cpp:236:(.text+0xad80): undefined reference to `vaExportSurfaceHandle'
ld: src/plugins/multimedia/ffmpeg/qffmpeghwaccel_vaapi.cpp:257:(.text+0xad95): undefined reference to `vaSyncSurface'
ld: src/plugins/multimedia/ffmpeg/qffmpeghwaccel_vaapi.cpp:327:(.text.unlikely+0x48a): undefined reference to `vaQueryVendorString'
collect2: error: ld returned 1 exit status

Change-Id: I407a67cb158acd19fd3afffd84b98ba496c59a62
Reviewed-by: Artem Dyomin <artem.dyomin@qt.io>
Reviewed-by: Tim Blechmann <tim.blechmann@qt.io>
(cherry picked from commit 2a61441bd2ffc3531fce4daac1de42cfa13fd4d7)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>